app:
  coinbase:
    base-url: https://api-public.sandbox.pro.coinbase.com
  mail:
    sender: sender@mail.com

spring:
  mail:
    host: 127.0.0.1
    password: password
    port: 3025
    test-connection: true
    username: username
